version: '3.1'

services: 
  loadbalancer:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
